#145 Bommel multi-tenant
hopps-app/hopps pull request #151
Opened 2024-11-20 16:10 UTC by schitcrafter

resolves #145

2024-11-21 17:33 UTC, d135-1r43 requested changes
Kannst du auch nochmal die Kaskaden in Tests absichern? Sonst schaut es ganz gut aus.

2024-11-21 17:33 UTC, d135-1r43 commented on backend/app.hopps.org/src/main/java/app/hopps/org/jpa/Bommel.java
> +    @OneToOne(mappedBy = "rootBommel", cascade = { CascadeType.DETACH, CascadeType.REFRESH, CascadeType.PERSIST, CascadeType.MERGE })
Brauchen wir hier nicht ALL?

2024-11-21 17:35 UTC, byte-sized-emi commented on backend/app.hopps.org/src/main/java/app/hopps/org/jpa/Bommel.java
> +    @OneToOne(mappedBy = "rootBommel", cascade = { CascadeType.DETACH, CascadeType.REFRESH, CascadeType.PERSIST, CascadeType.MERGE })
ALL würde auch delete cascaden, weiß nicht ob wir des wollen... ich hätte eher nein gesagt

2024-11-21 17:37 UTC, schitcrafter commented
Wie meinst du Kaskaden absichern? Ich wüsste nur wirklich wie ich PERSIST/MERGE testen könnte...außerdem funktionieren die eh nur in Org -> Bommel Richtung und nicht andersrum.
(Oh und FYI ich bin noch nicht fertig, muss noch organization tests fixen)

2024-11-28 09:30 UTC, d135-1r43 requested changes

2024-11-28 09:30 UTC, d135-1r43 commented on backend/app.hopps.org/src/main/java/app/hopps/org/jpa/Bommel.java
>  import jakarta.persistence.*;
Bitte kein *

2024-11-28 09:30 UTC, d135-1r43 commented on backend/app.hopps.org/src/main/java/app/hopps/org/jpa/Organization.java
> +import jakarta.persistence.*;
Kein *

2024-11-28 09:30 UTC, d135-1r43 commented on backend/app.hopps.org/src/main/java/app/hopps/org/rest/BommelResource.java
>  import jakarta.ws.rs.*;
Kein *

2024-11-28 09:30 UTC, d135-1r43 commented on backend/app.hopps.org/src/test/java/app/hopps/org/jpa/BommelTest.java
Kannst du den Hashcode und Equals Contract bitte noch testen? https://jqno.nl/equalsverifier/

2024-11-28 10:30 UTC, schitcrafter commented on backend/app.hopps.org/src/test/java/app/hopps/org/jpa/BommelTest.java
Wir hatten miteinander einen call wo wir rausgefunden hatten, dass wegen hibernate der equals verifier nicht funktioniert. Wenn es dafür keinen fix gibt kann ich den nicht einbauen

2024-12-01 17:24 UTC, d135-1r43 approved these changes

2024-12-01 17:24 UTC, merged