99 service fr zugferd fixed branch
hopps-app/hopps pull request #207
Opened 2024-12-21 02:01 UTC by Josh1ku

2024-12-22 16:02 UTC, d135-1r43 requested changes
Bitte auch nochmal komplett sauber alles formatieren mit dem Auto-Formatter der IDE

2024-12-22 16:02 UTC, d135-1r43 commented on backend/app.hopps.zugferd-document-service/src/main/java/app/hopps/model/InvoiceDocument.java
> +public record InvoiceDocument(String URL) {
Use URI, as URL is deprecated sind 2.0

2024-12-22 16:02 UTC, d135-1r43 commented on backend/app.hopps.zugferd-document-service/src/main/java/app/hopps/KafkaConnector.java
> +    @Incoming("document-URL-in")
Use all lower case IDs

2024-12-22 16:02 UTC, d135-1r43 commented on backend/app.hopps.zugferd-document-service/src/main/java/app/hopps/KafkaConnector.java
> +            throw new RuntimeException(e);
Log the exception

2024-12-22 16:02 UTC, d135-1r43 commented on backend/app.hopps.zugferd-document-service/src/test/java/app.hopps/ZugFerdServiceTest.java
> +    @Tag("zugferd")
Why the tag?

2024-12-22 16:02 UTC, d135-1r43 commented on backend/app.hopps.zugferd-document-service/src/test/java/app.hopps/ZugFerdServiceTest.java
> +package app.hopps;
Package does not match folder

2024-12-22 16:02 UTC, d135-1r43 commented on backend/app.hopps.zugferd-document-service/src/test/java/app.hopps/ZugFerdServiceTest.java
> +    public void shouldAnalyzeInvoiceWithZugferd() throws Exception {
Tests should be default protected

2024-12-22 16:02 UTC, d135-1r43 commented on backend/app.hopps.zugferd-document-service/src/test/java/app.hopps/ZugFerdServiceTest.java
> +    public void shouldAnalyzeInvoiceWithZugferd() throws Exception {
Exception cannot be thrown

2024-12-23 19:45 UTC, d135-1r43 commented
@Josh1ku, bitte das Feedback umsetzen und dann den Draft Status entfernen.

2024-12-24 00:26 UTC, Josh1ku commented on backend/app.hopps.zugferd-document-service/src/test/java/app.hopps/ZugFerdServiceTest.java
> +package app.hopps;
what would be the appropriate package?

2024-12-24 10:34 UTC, d135-1r43 requested changes

2024-12-24 10:34 UTC, d135-1r43 commented on backend/app.hopps.zugferd-document-service/src/main/java/app/hopps/KafkaConnector.java
> +            LOGGER.error(e.toString());
Ruhig die Oberklasse `Exception e` catchen. 
Nicht `LOGGER`, sondern `LOG` ist unser Standard.

2024-12-28 11:29 UTC, d135-1r43 approved these changes

2024-12-28 11:30 UTC, merged