Add files via upload
hopps-app/hopps pull request #78
Opened 2024-10-10 12:57 UTC by zom5583

2024-10-10 17:42 UTC, d135-1r43 approved these changes
Sehr gut! Habe nur Kleinigkeiten geändert und die letzten Schritte der Anmeldung zusammengefasst. 

@manuelhummler, kannst du auch nochmal reviewen?

2024-10-10 22:50 UTC, manuelhummler commented
<img width="170" alt="image" src="https://github.com/user-attachments/assets/4e250c28-c98b-477c-9b68-e281cdc3f5fa">
An dieser stelle bin ich noch nicht ganz sicher. 
Wir sollten das Passwort vermutlich nicht über den User Task Rest Request selbst setzen, da ansonsten ein Passwort in den prozessinstanzen rumfliegt. Zumindest wäre das bei Flowable so. Außerdem muss irgendwo ja noch geprüft werden, ob das gesetzte Passwort den Kriterien entspricht, z.B. in einem Service Task, um das Gateway anschließend ausführen zu können. Die Prüfung selbst sollte ja vermutlich nicht im Gateway erst passieren. Da bin ich aber offen für Diskussionen und bin gespannt auf eure Meinung @zom5583 und @d135-1r43

2024-10-10 22:57 UTC, manuelhummler commented
Außerdem frage ich mich, wann und von wem die Nachricht mit der Erfolgsnachricht geschickt wird?
<img width="455" alt="image" src="https://github.com/user-attachments/assets/7f346261-0c7e-4d70-a33a-458ab4094bcf">
An wen wird die darauf folgende Nachricht gesendet?

2024-10-10 23:02 UTC, manuelhummler requested changes
Bitte noch prüfen, was mit den Nachrichten passiert, wie in den Kommentaren beschrieben.

2024-10-11 09:52 UTC, d135-1r43 commented
> <img alt="image" width="170" src="https://private-user-images.githubusercontent.com/25209702/375567052-4e250c28-c98b-477c-9b68-e281cdc3f5fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg2NDA1NTYsIm5iZiI6MTcyODY0MDI1NiwicGF0aCI6Ii8yNTIwOTcwMi8zNzU1NjcwNTItNGUyNTBjMjgtYzk4Yi00NzdjLTliNjgtZTI4MWNkYzNmNWZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDExVDA5NTA1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5MzVhOGE1ZjAyYTgzYTJjODM4MWZmZjQ5MjI1ZTk0ZTdiOGFiYjUwNWUwOGJkZTExMmFmMGI5OWZiZDQ4NmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.eNfiDufb4uoPwXCI-dl522e37GAc4oyp09R-sX84eXY"> An dieser stelle bin ich noch nicht ganz sicher. Wir sollten das Passwort vermutlich nicht über den User Task Rest Request selbst setzen, da ansonsten ein Passwort in den prozessinstanzen rumfliegt. Zumindest wäre das bei Flowable so. Außerdem muss irgendwo ja noch geprüft werden, ob das gesetzte Passwort den Kriterien entspricht, z.B. in einem Service Task, um das Gateway anschließend ausführen zu können. Die Prüfung selbst sollte ja vermutlich nicht im Gateway erst passieren. Da bin ich aber offen für Diskussionen und bin gespannt auf eure Meinung @zom5583 und @d135-1r43

Das ist jetzt die Frage wie man es modellieren mag. Technisch wird der Keycloak das machen. Man kann es jetzt entweder "zur Dokumentation" modellieren oder es komplett in einen Subprozess packen, der dann technisch durch Keycloak implementiert wird.

2024-10-19 14:13 UTC, zom5583 commented
Hallo zusammen @Kleinhummel @d135-1r43 , 

danke für das Feedback :) 

Ich habe die Änderungen vorgenommen. 

@manuelhummler du hast mit der Überprüfung der Kriterien recht. Das habe ich auch angepasst.

2024-10-19 16:57 UTC, d135-1r43 commented
@manuelhummler Wenn so fein für dich, würde ich gern mergen. Ich bin zufrieden.

2024-10-21 10:58 UTC, manuelhummler approved these changes

2024-10-21 19:09 UTC, merged